#!/bin/bash

cp /usr/local/etc/minecraft/minecraft_server.jar /data/
cp /usr/local/etc/minecraft/minecraft_forge-installer.jar /data/

cd /data/ && java -jar minecraft_forge-installer.jar  --installServer && mv minecraftforge*.jar minecraftforge.jar

if [ ! -f /data/opts.txt ]
then
    cp /usr/local/etc/minecraft/opts.txt /data/
fi

if [ ! -f /data/white-list.txt ]
then
    cp /usr/local/etc/minecraft/white-list.txt /data/
fi

if [ ! -f /data/server.properties ]
then
    cp /usr/local/etc/minecraft/server.properties /data/
fi

# Run supervisor which maintains the mumble server
/usr/bin/supervisord

